include:
  - project: 'commun/cicd-templates'
    file: 'static_web.yaml'

variables:
  DEPLOY_WHAT: front
  SOURCE_DIR: apps/backoffice
  BUILD_DIR: apps/backoffice/dist
#Keywords exemple : front/middle/back/all

stages:
  - prepare
  - build
  - test
  - release
  - deploy


web_build:
  image: node:18-alpine
  script:
    - npm install -g pnpm
    - pnpm install
    - cp $SOURCE_DIR/.env.$DEPLOY_TARGET_ENVIRONMENT $BUILD_DIR/.env
    - pnpm run build
 
#######################################
# Deploy Jobs
#######################################

deploy:
  stage: deploy
  variables:
    PACKAGE_URL: $PACKAGE_URL
  trigger: 
    project: "applications/projetrti/deploiement"
    # branch: v1.0.0
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    # Déploiement en prod avec Tag protégé
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED
    # Déploiement en dev sur Commit sur la branche dev et sur MR sur main ou dev.
    - if: $CI_COMMIT_BRANCH == "dev" && $DEPLOY_TARGET_ENVIRONMENT == "dev"
    - if: ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "$CI_DEFAULT_BRANCH" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" )  && $CI_PIPELINE_SOURCE == 'merge_request_event'


