include:
  - project: 'commun/cicd-templates'
    file: 'static_web.yaml'

variables:
  DEPLOY_WHAT: front 
  BUILD_DIR: apps/backoffice/dist
#Keywords exemple : front/middle/back/all

stages:
  - prepare
  - build
  - test
  - release
  - deploy


web_build:
  image: node:18-alpine
  script:
    - echo "## Build"
    - npm install -g pnpm
    - pnpm run build
    - mkdir build
    - export MYPWD=$PWD
    - test -e $BUILD_DIR || mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - tar -cz --exclude="build" --exclude=".git*" -f ${MYPWD}/build/${APPLICATION_NAME}.tgz .

#######################################
# Deploy Jobs
#######################################

deploy:
  stage: deploy
  variables:
    PACKAGE_URL: $PACKAGE_URL
  trigger: 
    project: "applications/demo/deploy"
    # branch: v1.0.0
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    # Déploiement en prod avec Tag protégé
    - if: $CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED
    # Déploiement en dev sur Commit sur la branche dev et sur MR sur main ou dev.
    - if: $CI_COMMIT_BRANCH == "dev" && $DEPLOY_TARGET_ENVIRONMENT == "dev"
    - if: ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "$CI_DEFAULT_BRANCH" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" )  && $CI_PIPELINE_SOURCE == 'merge_request_event'

      

